### ISSUE TITLE
Add djLint to Pre-commit Hooks for HTML Formatting

### ISSUE THREAD

**Issue by BDadmehr0** [Yadgah/Yadgah#173]
**Description:**

Please add [`[djLint](https://github.com/Riverside-Healthcare/djLint)`](https://github.com/Riverside-Healthcare/djLint) to the project's `.pre-commit-config.yaml` in order to automatically format and lint Django template files (`.html`, `.jinja`, etc.). This helps maintain consistent, readable HTML across the project.

**Suggested Configuration:**

```yaml
- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.34.4
  hooks:
    - id: djlint
      args: [--reformat, --profile=djangotemplate]
      files: \.(html|jinja|j2)$
```

**Next Steps:**

After adding and installing the hook via:

```bash
pre-commit install
pre-commit run --all-files
```

Please test to ensure all HTML templates load properly in the app, especially those with Django templating logic like `{% if %}`, `{% for %}`, and `{{ variable }}`. `djLint` generally handles Django syntax well, but it's best to verify in the actual runtime context.

Thanks!
